# docker-compose.yml
version: "3"
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql://user:password@db/db